/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gittab_basic_natives_NativeTest */

#ifndef _Included_net_gittab_basic_natives_NativeTest
#define _Included_net_gittab_basic_natives_NativeTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_gittab_basic_natives_NativeTest
 * Method:    test
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_net_gittab_basic_natives_NativeTest_test__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     net_gittab_basic_natives_NativeTest
 * Method:    test
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_gittab_basic_natives_NativeTest_test__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
