server:
  port: 8080
spring:
  application:
    name: fsm-sample
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/fsm_sample?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
  cache:
    type: redis
  jpa:
    show-sql: false

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true


logging:
  level:
    net:
      gittab: info